### ISSUE TITLE
JSON Payload to associate Person with Address

### ISSUE THREAD

**Issue by iammyr** [olivebh/play-slick#2]
Thanks a lot OliveBH Dev Team for this great tutorial!
I am now running your application perfectly. I manage to POST new addresses and new persons with empty address list. 

However, when I try to POST a person completed with list of addresses, I get 400 Bad request. Here follow the details of the request I submit:

_POST http://localhost:9000/persons_
Headers:

```
Accept: *.*
Content-Type: application/json
```

Payload:

```
{"personId" : 1,
    "name" : "Serif",
    "phones" : [
        { "phoneId" : 0, "number" : "+353851148224" },
        { "phoneId" : 10, "number" : "+387 61/000-333" }
    ],
    "addresses" : [ {"addressId" : 1}]
}
```

I've also tried:

```
{
    "personId" : 4,
    "name" : "Serif",
    "phones" : [
        { "phoneId" : 9, "number" : "+387 61/000-222" },
        { "phoneId" : 10, "number" : "+387 61/000-333" }
    ],
    "addresses" : [
        { "addressId" : 2, "street" : "Ferhadija" },
        { "addressId" : 3,  "street" : "Gechet" }
    ]
}
```

So far the only request that returns 200 OK is the following:

```
{
    "personId" : 4,
    "name" : "Serif",
    "phones" : [
        { "phoneId" : 9, "number" : "+387 61/000-222" },
        { "phoneId" : 10, "number" : "+387 61/000-333" }
    ],
    "addresses" : []
}
```

So I wonder, how can I specify a reference between a person and an address via your RESTful API? Thanks in advance!

**Comment by iammyr** [comment]
issue solved: during the new person creation, I was accidentally referencing addresses that were not existent yet (I hadn't yet created them via POST /addresses).

**Comment by olivebh** [comment]
You're welcome, glad you managed to solve the issue! :)
